### ISSUE TITLE
Brozzler-easy issue after start

### ISSUE THREAD

**Issue by yacylover** [internetarchive/brozzler#267]
Hi,

I successfully installed brozzler-easy via brew. After entering the command brozzler-easy in zsh the following error is being thrown:

`2023-11-20 14:49:48,196 17658 ERROR MainThread root.init_app(wsgi_wrappers.py:169) *** pywb app init FAILED config from "create_wb_router"!
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/pywb/framework/wsgi_wrappers.py", line 166, in init_app
    wb_router = init_func(config)
  File "/Library/Python/3.8/site-packages/pywb/webapp/pywb_init.py", line 256, in create_wb_router
    defaults = load_yaml_config(DEFAULT_CONFIG)
  File "/Library/Python/3.8/site-packages/pywb/utils/loaders.py", line 49, in load_yaml_config
    config = yaml.load(configdata)
TypeError: load() missing 1 required positional argument: 'Loader'
Traceback (most recent call last):
  File "/usr/local/bin/brozzler-easy", line 10, in <module>
    sys.exit(main())
  File "/Library/Python/3.8/site-packages/brozzler/easy.py", line 273, in main
    controller = BrozzlerEasyController(args)
  File "/Library/Python/3.8/site-packages/brozzler/easy.py", line 128, in __init__
    self.pywb_httpd = self._init_pywb(args)
  File "/Library/Python/3.8/site-packages/brozzler/easy.py", line 176, in _init_pywb
    wsgi_app = pywb.framework.wsgi_wrappers.init_app(
  File "/Library/Python/3.8/site-packages/pywb/framework/wsgi_wrappers.py", line 166, in init_app
    wb_router = init_func(config)
  File "/Library/Python/3.8/site-packages/pywb/webapp/pywb_init.py", line 256, in create_wb_router
    defaults = load_yaml_config(DEFAULT_CONFIG)
  File "/Library/Python/3.8/site-packages/pywb/utils/loaders.py", line 49, in load_yaml_config
    config = yaml.load(configdata)
TypeError: load() missing 1 required positional argument: 'Loader'
bash-3.2$ brozzler-easy
/Library/Python/3.8/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
2023-11-20 14:50:34,352 17668 INFO MainThread root.stats_processor(controller.py:65) statistics tracking disabled
2023-11-20 14:50:34,353 17668 INFO MainThread warcprox.warcproxy.WarcProxy.__init__(mitmproxy.py:617) 100 proxy threads
2023-11-20 14:50:34,358 17668 NOTICE MainThread warcprox.warcproxy.WarcProxy.server_activate(warcproxy.py:493) listening on 127.0.0.1:56467
2023-11-20 14:50:34,376 17668 ERROR MainThread root.init_app(wsgi_wrappers.py:169) *** pywb app init FAILED config from "create_wb_router"!
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/pywb/framework/wsgi_wrappers.py", line 166, in init_app
    wb_router = init_func(config)
  File "/Library/Python/3.8/site-packages/pywb/webapp/pywb_init.py", line 256, in create_wb_router
    defaults = load_yaml_config(DEFAULT_CONFIG)
  File "/Library/Python/3.8/site-packages/pywb/utils/loaders.py", line 49, in load_yaml_config
    config = yaml.load(configdata)
TypeError: load() missing 1 required positional argument: 'Loader'
Traceback (most recent call last):
  File "/usr/local/bin/brozzler-easy", line 10, in <module>
    sys.exit(main())
  File "/Library/Python/3.8/site-packages/brozzler/easy.py", line 273, in main
    controller = BrozzlerEasyController(args)
  File "/Library/Python/3.8/site-packages/brozzler/easy.py", line 128, in __init__
    self.pywb_httpd = self._init_pywb(args)
  File "/Library/Python/3.8/site-packages/brozzler/easy.py", line 176, in _init_pywb
    wsgi_app = pywb.framework.wsgi_wrappers.init_app(
  File "/Library/Python/3.8/site-packages/pywb/framework/wsgi_wrappers.py", line 166, in init_app
    wb_router = init_func(config)
  File "/Library/Python/3.8/site-packages/pywb/webapp/pywb_init.py", line 256, in create_wb_router
    defaults = load_yaml_config(DEFAULT_CONFIG)
  File "/Library/Python/3.8/site-packages/pywb/utils/loaders.py", line 49, in load_yaml_config
    config = yaml.load(configdata)
TypeError: load() missing 1 required positional argument: 'Loader'
`

Can someone help me please?

Best regards,

Steve

**Comment by yacylover** [comment]
Can anybody help me please with this issue? I would love to try out Brozzler since I'm addicted to web archiving :-)

**Comment by yacylover** [comment]
Can anybody help me please with this issue? I would love to try out Brozzler because I'm addicted to web archiving :-)
