### ISSUE TITLE
Brozzler scrapes only single page.

### ISSUE THREAD

**Issue by Scrip7** [internetarchive/brozzler#28]
Brozzler doesn't crawl, extracts and follows all the links on the website, it only scrapes the main page (the url from job.yaml configuration file). 

I guess something's wrong with my scope surt parameter? But scope rules are not yet documented and I don't know where else I can find the information about it, so I've decided to ask here.

I've tried the following scope configurations:

1. I've made surt rules with this module: [https://github.com/internetarchive/surt](https://github.com/internetarchive/surt)

_// job.yaml file_
```
#other job parameters
seeds:
  url: http://iskme.org
    scope:
      surt: org,iskme)/
```

2.Surt rules according to this documentation: [https://webarchive.jira.com/wiki/display/ARIH/SURT+Rules](https://webarchive.jira.com/wiki/display/ARIH/SURT+Rules)

_// job.yaml file_
```
#other job parameters
seeds:
  url: http://iskme.org 
    scope:
      surt: +http://(org,iskme,
```

But it still scrapes only one main page iskme.org. How do I configure brozzler scope rules to crawl all of the website, to follow all the links for the whole domain?

**Comment by nlevitt** [comment]
This job.yml works for me:
```
---
id: scrip7-001
seeds:
- url: http://iskme.org 
  scope:
    surt: http://(org,iskme,
```

The example in the readme shows a surt in that format. Maybe brozzler should also accept the `+surt` format.

In your case are you sure you need that surt? If you run `brozzler-new-site http://iskme.org` the default scope surt will be `http://(org,iskme,)/`. The difference between that surt and yours is that yours scopes in subdomains. Maybe you need that, but if not, you can let brozzler figure out the scope for you.

**Comment by Scrip7** [comment]
`brozzler-new-site http://iskme.org` or job configuration `surt: http://(org,iskme, ` didn't work for me. Brozzler keeps crawling the same main page. 

But may be it's a completely different issue and not about the scope. I have another issue with runnung Brozzler: chrome crashes. 
It shows "about:blank" page and closes in a second without rendering anything. Then it repeats again and again till I press Ctrl+C trying to get the same page, opening/closing blank chrome. 

When I run `brozzler-worker` I keep getting this error:
```
2016-12-06 04:43:37,597 19537 INFO BrozzlingThread:http://iskme.org brozzler.browser.Chrome.start(browser.py:639) got chrome window websocket debug url ws://localhost:9217/devtools/page/257cb07c-39c0-401b-8c38-803e6ef260d6 from http://localhost:9217/json
2016-12-06 04:43:38,599 19537 CRITICAL BrozzlingThread:http://iskme.org brozzler.worker.BrozzlerWorker._brozzle_site(worker.py:352) unexpected exception
Traceback (most recent call last):
  File "/home/archive/archive.org/env3/lib/python3.4/site-packages/brozzler-1.1b8.dev130-py3.4.egg/brozzler/worker.py", line 335, in _brozzle_site
    outlinks = self.brozzle_page(browser, site, page)
  File "/home/archive/archive.org/env3/lib/python3.4/site-packages/brozzler-1.1b8.dev130-py3.4.egg/brozzler/worker.py", line 280, in brozzle_page
    on_url_change=page.note_redirect)
  File "/home/archive/archive.org/env3/lib/python3.4/site-packages/brozzler-1.1b8.dev130-py3.4.egg/brozzler/browser.py", line 278, in browse_page
    if self._browse_interval_func():
  File "/home/archive/archive.org/env3/lib/python3.4/site-packages/brozzler-1.1b8.dev130-py3.4.egg/brozzler/browser.py", line 410, in _browse_interval_func
    self._websocket_url))
brozzler.browser.BrowsingException: websocket closed, did chrome die? ws://localhost:9217/devtools/page/257cb07c-39c0-401b-8c38-803e6ef260d6
```

**Comment by nlevitt** [comment]
What version of chrome/chromium on what platform?

If you run brozzler-worker with --trace it will log all the messages from the browser. That might give a hint as to what's happening.

But probably the best I can suggest is trying a different version. Or, if you're using chromium, try chrome, or vice versa. You could also try chrome canary (the beta version basically).

**Comment by Scrip7** [comment]
I'm on Debian Jessie.

I've tried: 
- Chromium 53.0.2785.143
- Google Chrome 54.0.2840.100
- Google Chrome 55.0.2883.75-1 (updated from Google Chrome 54)
- Google Chrome 56.0.2924.14 dev

If I run brozzler-worker with `--trace` I get additional error message about verification certificate. But brozzler runs Chrome with `--ignore-certificate-errors` flag, so I don't think it's the issue.

```
2016-12-06 19:18:35,305 17170 Level 5 ChromeOutReaderThread(pid=17295) root._read_stderr_stdout(browser.py:689) chrome pid 17295 STDOUT b'[17295:17317:1206/191834:ERROR:cert_verify_proc_nss.cc(942)] CERT_PKIXVerifyCert for translate.googleapis.com failed err=-8179\n'
2016-12-06 19:18:35,531 17170 CRITICAL BrozzlingThread:http://iskme.org brozzler.worker.BrozzlerWorker._brozzle_site(worker.py:352) unexpected exception
Traceback (most recent call last):
  File "/home/archive/archive.org/env3/lib/python3.4/site-packages/brozzler-1.1b8.dev130-py3.4.egg/brozzler/worker.py", line 335, in _brozzle_site
    outlinks = self.brozzle_page(browser, site, page)
  File "/home/archive/archive.org/env3/lib/python3.4/site-packages/brozzler-1.1b8.dev130-py3.4.egg/brozzler/worker.py", line 280, in brozzle_page
    on_url_change=page.note_redirect)
  File "/home/archive/archive.org/env3/lib/python3.4/site-packages/brozzler-1.1b8.dev130-py3.4.egg/brozzler/browser.py", line 278, in browse_page
    if self._browse_interval_func():
  File "/home/archive/archive.org/env3/lib/python3.4/site-packages/brozzler-1.1b8.dev130-py3.4.egg/brozzler/browser.py", line 410, in _browse_interval_func
    self._websocket_url))
brozzler.browser.BrowsingException: websocket closed, did chrome die? ws://localhost:9201/devtools/page/28dfa485-0f68-463a-8802-6747ef7c7051
```
May be I should try older Chrome/Chromium versions (because as I understand those that I've tried are the latest, at least for Linux).

**Comment by nlevitt** [comment]
Thanks for trying different versions of chrome. Disappointing that they all crash. I wonder if they don't like one of the command line options brozzler uses. 
```
chromium --use-mock-keychain --user-data-dir=/tmp/tmpxtgpge9o/chrome-user-data --remote-debugging-port=9222 --disable-web-sockets --disable-cache --window-size=1100,900 --no-default-browser-check --disable-first-run-ui --no-first-run --homepage=about:blank --disable-direct-npapi-requests --disable-web-security --disable-notifications --disable-extensions --disable-save-password-bubble about:blank
```

You could try running that command on its own and see if it crashes. If so, try removing the options one at a time to see if one of them is the culprit.

Could you also attach the complete log from brozzler-worker?

**Comment by Scrip7** [comment]
I've tried the command, nothing crashes: chrome opens about:blank page. 

Attaching logs from brozzler-worker (running with `--trace` option).
[brozzler-worker.log.txt](https://github.com/internetarchive/brozzler/files/635372/brozzler-worker.log.txt)
