### ISSUE TITLE
Occasional brozzler hangs while scanning a large site.

### ISSUE THREAD

**Issue by detrout** [internetarchive/brozzler#33]
I managed to catch the exception.

its on debian using chromium Version: 55.0.2883.75-1~deb8u1

2017-02-04 22:36:24,671 1736 INFO WarcWriterThread(tid=1743) warcprox.writer.WarcWriter.close_writer(writer.py:69) closing brozzler-20170205063139292-00094-vs75mxwt.warc.gz
2017-02-04 22:37:09,419 1736 CRITICAL BrozzlingThread:https://www.ncdc.noaa.gov/sotc brozzler.worker.BrozzlerWorker._brozzle_site(worker.py:360) unexpected exception
Traceback (most recent call last):
  File "/home/diane/.virtualenvs/brozzler/lib/python3.4/site-packages/brozzler-1.1b9.dev175-py3.4.egg/brozzler/worker.py", line 341, in _brozzle_site
    outlinks = self.brozzle_page(browser, site, page)
  File "/home/diane/.virtualenvs/brozzler/lib/python3.4/site-packages/brozzler-1.1b9.dev175-py3.4.egg/brozzler/worker.py", line 285, in brozzle_page
    on_screenshot=_on_screenshot)
  File "/home/diane/.virtualenvs/brozzler/lib/python3.4/site-packages/brozzler-1.1b9.dev175-py3.4.egg/brozzler/browser.py", line 430, in browse_page
    user_agent=user_agent, timeout=300)
  File "/home/diane/.virtualenvs/brozzler/lib/python3.4/site-packages/brozzler-1.1b9.dev175-py3.4.egg/brozzler/browser.py", line 480, in navigate_to_page
    timeout=timeout)
  File "/home/diane/.virtualenvs/brozzler/lib/python3.4/site-packages/brozzler-1.1b9.dev175-py3.4.egg/brozzler/browser.py", line 291, in _wait_for
    elapsed, callback))
brozzler.browser.BrowsingTimeout: timed out after 300.1s waiting for: <function Browser.navigate_to_page.<locals>.<lambda> at 0x7fa2ea0a8d08>
2017-02-04 22:37:09,426 1736 INFO BrozzlingThread:https://www.ncdc.noaa.gov/sotc brozzler.browser.Browser.stop(browser.py:344) shutting down websocket connection
2017-02-04 22:37:09,443 1736 INFO BrozzlingThread:https://www.ncdc.noaa.gov/sotc brozzler.chrome.Chrome.stop(chrome.py:267) terminating chrome pgid 13222
2017-02-04 22:37:09,974 1736 INFO BrozzlingThread:https://www.ncdc.noaa.gov/sotc

**Comment by nlevitt** [comment]
I've seen the same thing, but so far I haven't been able to isolate or reproduce it. My suspicion is there is some browser misbehavior in play. Or it could be something on the warcprox side. Have to solve this, but I'm not sure how right now.

**Comment by nlevitt** [comment]
I wrote on an issue in our internal tracker

> Discovered that the problem we've been seeing of timeouts waiting for page load is because of urls with hash tags. Suppose brozzler brozzles http://example.com/, then chooses the next page to brozzle for that site. It happens to pick http://example.com/#somehashtag. Navigating to that page does not result in a page load event ("Page.loadEventFired" from the debugging protocol), so brozzler hangs until the 5 minute timeout waiting for that event. This scenario happens frequently and has a major performance impact.

I believe https://github.com/internetarchive/brozzler/commit/3d47805ec solves this issue. Resolving. Please let me know if you continue to see the problem.
