### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'rethinkdb_dedup_url'

### ISSUE THREAD

**Issue by thomaspreeceBBC** [internetarchive/brozzler#79]
Trying to use the brozzler easy setup on Ubuntu 16.04.
Using Anaconda with a fresh environment:
```
conda create --name Brozzler python=3.5
source activate Brozzler 
pip install brozzler[easy]
```

Running:
```
brozzler-easy
```
produces the error:

```
Traceback (most recent call last):
  File "/home/thomaspr/anaconda3/envs/Brozzler/bin/brozzler-easy", line 11, in <module>
    sys.exit(main())
  File "/home/thomaspr/anaconda3/envs/Brozzler/lib/python3.5/site-packages/brozzler/easy.py", line 274, in main
    controller = BrozzlerEasyController(args)
  File "/home/thomaspr/anaconda3/envs/Brozzler/lib/python3.5/site-packages/brozzler/easy.py", line 126, in __init__
    self._warcprox_args(args))
  File "/home/thomaspr/anaconda3/envs/Brozzler/lib/python3.5/site-packages/warcprox/main.py", line 213, in init_controller
    if args.rethinkdb_dedup_url:
AttributeError: 'Namespace' object has no attribute 'rethinkdb_dedup_url'
```

**Comment by nlevitt** [comment]
Thanks for the report! Will fix soon.

**Comment by nlevitt** [comment]
This should be fixed. There are new versions of brozzler and warcprox up on pypi now. Please reopen if you still have problems.
