### ISSUE TITLE
Unable to get started based on README

### ISSUE THREAD

**Issue by machawk1** [internetarchive/brozzler#8]
I attempted to use this software per the Installation and Usage instructions in the project README and am unable to get far. I first install `rethinkdb`:

```sh
brew update && brew install rethinkdb
```
then install brozzler per the README instructions:
```sh
pip install brozzler
```
I attempt the first command in the Usage section of the README but receive an error:
```sh
$ brozzler-worker -e chromium
Traceback (most recent call last):
  File "/usr/local/bin/brozzler-worker", line 4, in <module>
    __import__('pkg_resources').run_script('brozzler==1.1.dev1', 'brozzler-worker')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/brozzler-1.1.dev1-py2.7.egg/EGG-INFO/scripts/brozzler-worker", line 8, in <module>
    import brozzler
  File "/usr/local/lib/python2.7/site-packages/brozzler-1.1.dev1-py2.7.egg/brozzler/__init__.py", line 48, in <module>
    from brozzler.site import Page, Site
  File "/usr/local/lib/python2.7/site-packages/brozzler-1.1.dev1-py2.7.egg/brozzler/site.py", line 12, in <module>
    class Site(brozzler.BaseDictable):
  File "/usr/local/lib/python2.7/site-packages/brozzler-1.1.dev1-py2.7.egg/brozzler/site.py", line 13, in Site
    logger = logging.getLogger(__module__ + "." + __qualname__)
NameError: name '__qualname__' is not defined
```
Figuring this might not be a fatal error, I also create a sample job based on the Job Configuration section of the README:

```sh
$ echo -e "id: test\nseeds:\n  - url: http://example.com" > testJob.yaml
$ brozzler-new-job testJob.yaml 
Traceback (most recent call last):
  File "/usr/local/bin/brozzler-new-job", line 4, in <module>
    __import__('pkg_resources').run_script('brozzler==1.1.dev1', 'brozzler-new-job')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/brozzler-1.1.dev1-py2.7.egg/EGG-INFO/scripts/brozzler-new-job", line 7, in <module>
    import brozzler
  File "/usr/local/lib/python2.7/site-packages/brozzler-1.1.dev1-py2.7.egg/brozzler/__init__.py", line 48, in <module>
    from brozzler.site import Page, Site
  File "/usr/local/lib/python2.7/site-packages/brozzler-1.1.dev1-py2.7.egg/brozzler/site.py", line 12, in <module>
    class Site(brozzler.BaseDictable):
  File "/usr/local/lib/python2.7/site-packages/brozzler-1.1.dev1-py2.7.egg/brozzler/site.py", line 13, in Site
    logger = logging.getLogger(__module__ + "." + __qualname__)
NameError: name '__qualname__' is not defined
```

* OS X 10.11.5
* Python 2.7.10 (Is this the issue due to warcprox needing py3?)

How do I get started with brozzler?

**Comment by nlevitt** [comment]
Brozzler requires python 3.4 or 3.5! I apologize, I haven't had time yet to write proper documentation.

**Comment by machawk1** [comment]
Switched to use brozzler w/ py3, fired up rethinkdb, and can now proceed. Thanks, @nlevitt
